
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Sintactico;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int PyC = 4;
  public static final int Fin = 3;
  public static final int Comer = 6;
  public static final int Aba = 18;
  public static final int Mover = 5;
  public static final int Hay = 11;
  public static final int No_Hay = 12;
  public static final int Arr = 17;
  public static final int Repite = 9;
  public static final int Inicio = 2;
  public static final int Izq = 15;
  public static final int Der = 16;
  public static final int EOF = 0;
  public static final int Limite = 13;
  public static final int Num = 19;
  public static final int Entonces = 8;
  public static final int If = 7;
  public static final int error = 1;
  public static final int Veces = 10;
  public static final int Manzana = 14;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "Inicio",
  "Fin",
  "PyC",
  "Mover",
  "Comer",
  "If",
  "Entonces",
  "Repite",
  "Veces",
  "Hay",
  "No_Hay",
  "Limite",
  "Manzana",
  "Izq",
  "Der",
  "Arr",
  "Aba",
  "Num"
  };
}

